version: "3.8"

services:
    nginx:
      container_name: nginx
      image: nginx:alpine
      ports:
        - "1903:80"
      depends_on:
        - app
        - db
      volumes:
        - ./src:/var/www
        - ./nginx/conf.d/:/etc/nginx/conf.d

    db:
      image: mysql
      container_name: mysql
      ports:
        - "3306:3306"
      volumes:
        - ./mysql/data:/var/lib/mysql
      environment:
        - MYSQL_DATABASE=laravel
        - MYSQL_ROOT_PASSWORD=AlanyaAsd123+

    app:
      container_name: app
      build:
        context: ./php
        dockerfile: Dockerfile
      volumes:
        - ./src:/var/www
      ports:
        - "9002:9002"
      working_dir: /var/www